# Generated by Django 4.2.1 on 2023-12-03 01:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-created_at", "replied"],
                "verbose_name": "mensagem",
                "verbose_name_plural": "mensagens",
            },
        ),
    ]
