# Generated by Django 4.2.1 on 2023-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="reply",
            field=models.TextField(blank=True, verbose_name="resposta"),
        ),
    ]
